# Generated by Django 4.2.10 on 2024-02-17 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0005_alter_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_booking', models.DateTimeField()),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('value', models.IntegerField()),
                ('status', models.CharField(default='Reservado', max_length=30)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
    ]
