# Generated by Django 5.0.1 on 2024-02-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='value',
            field=models.IntegerField(max_length=50),
        ),
    ]
