# Generated by Django 5.0.1 on 2024-01-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('value', models.FloatField(max_length=50)),
                ('image', models.ImageField(null=True, upload_to='static/images_project')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
