# Generated by Django 5.0.1 on 2024-02-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_service_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='value',
            field=models.IntegerField(max_length=50),
        ),
    ]
