# Generated by Django 5.0.1 on 2024-01-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabin',
            name='image',
            field=models.ImageField(null=True, upload_to='static/services_images'),
        ),
    ]
