# Generated by Django 5.0.1 on 2024-01-30 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabins', '0002_alter_cabin_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabin',
            name='capacity',
            field=models.IntegerField(),
        ),
    ]
