# Generated by Django 4.2.10 on 2024-02-17 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabins', '0005_alter_cabin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabin',
            name='value',
            field=models.IntegerField(),
        ),
    ]
