# Generated by Django 4.2.10 on 2024-02-17 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('services', '0008_alter_service_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking_service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bookings.booking')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='services.service')),
            ],
        ),
    ]
